gcc -o mytail mytail.c
gcc -o myls myls.c
gcc -o myps myps.c
gcc -o main main.c
gcc -o mypwd mypwd.c
gcc -o mymkdir mymkdir.c
gcc -o mycat mycat.c
gcc -o mycd mycd.c
gcc -o mymv mymv.c
gcc -o myrm myrm.c
